server:
  port: ${PORT:5001}

spring:
  mvc:
    log-request-details: true
  codec:
    log-request-details: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://connect-application-api.hml.gingapay.io/oauth/check_token
          client-id: eb3cb944-d1b6-4360-88df-72e27be4c2d2
          client-secret: secret
  datasource:
    url: jdbc:postgresql://localhost:25432/dbtemplate
    username: connect_development
    password: p25Hb3Xy5PAhys4CkJTsmhXh
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    filter: true
    persistAuthorization: true
