server:
  port: ${PORT:5000}
  servlet:
    context-path: /
  error:
    include-message: always

spring:
  application:
    name: template-application
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://connect-application-api.hml.gingapay.io/oauth/check_token
          client-id: eb3cb944-d1b6-4360-88df-72e27be4c2d2
          client-secret: secret
  datasource:
    url: jdbc:postgresql://104.131.1.128:25432/dbaccount
    username: connect_development
    password: p25Hb3Xy5PAhys4CkJTsmhXh
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO
      filter:
        CommonsRequestLoggingFilter: INFO
    com.gingapay.templateapplicationapi.resource: INFO

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    filter: true
    persistAuthorization: true
