server:
  port: ${PORT:5000}
  servlet:
    context-path: /
  error:
    include-message: always

spring:
  application:
    name: template-application
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${CONNECT_INTROSPECTION_URI}
          client-id: ${CONNECT_CLIENT_ID}
          client-secret: ${CONNECT_CLIENT_SECRET}
  datasource:
    url: ${DATABASE_CONNECTION_STRING}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO
      filter:
        CommonsRequestLoggingFilter: INFO
    com.gingapay.templateapplication.resource: INFO

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    filter: true
    persistAuthorization: true
