version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=connect_development
      - POSTGRES_PASSWORD=p25Hb3Xy5PAhys4CkJTsmhXh
      - POSTGRES_DB=dbtemplate
    ports:
      - '25432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
